spring:
  application:
    name: church-crm-api
  config:
    import: optional:file:.env[.properties]

  modulith:
    events:
      jdbc:
        schema-initialization:
          enabled: true
    runtime:
      flyway-enabled: true

  security:
    enabled: ${SECURITY_ENABLED:true}
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/church-cms}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  datasource:
    url: jdbc:postgresql://localhost:5432/church
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

keycloak:
  admin:
    server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8080}
    realm: ${KEYCLOAK_REALM:church-cms}
    client-id: ${KEYCLOAK_CLIENT_ID:church-cms-api}
    client-secret: ${KEYCLOAK_CLIENT_SECRET:0D707122-4A11-4889-869B-4752CAEDECCD}

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    oauth:
      client-id: church-cms-ui
      client-secret: 27074815-E8EF-469A-A183-DE11B802F90B
      use-pkce-with-authorization-code-grant: true
  show-actuator: false
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  # Disable Querydsl support since we're not using it
  querydsl:
    enabled: false

logging:
  level:
    org.springframework.modulith: DEBUG
    org.churchcrm.churchcrmapi: DEBUG
    org.springframework.context.event: DEBUG
    org.flywaydb: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: TRACE

server:
  port: 8081
